server:
  port: 8080 #端口
spring:
  application:
    name: mq-provider-war #服务名称

#配置rabbitMq 服务器
  rabbitmq:
    host: 39.107.141.198
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
    virtual-host: my_vhost
